### ISSUE TITLE
Crashes trying to vetorize to empty gerber file / silkscreen layer

### ISSUE THREAD

**Issue by dokutan** [jaseg/gerbolyze#4]
When trying to add the image to an empty silkscreen layer the program crashes.
```
Traceback (most recent call last):
  File "/home/-/.local/bin/gerbolyze", line 32, in <module>
    gerbolyze.process_gerbers(args.source, args.target, args.image, args.side, args.layer, args.debugdir)
  File "/home/-/.local/lib/python3.7/site-packages/gerbolyze.py", line 343, in process_gerbers
    out = paste_image(tgrb, ogrb, source_img, [subtract], debugdir=debugdir, status_print=lambda *args: print(*args, flush=True))
  File "/home/-/.local/lib/python3.7/site-packages/gerbolyze.py", line 208, in paste_image
    status_print=lambda *args: status_print('   ', *args))
  File "/home/-/.local/lib/python3.7/site-packages/gerbolyze.py", line 234, in plot_contours
    aperture = list(layer.apertures)[0]
IndexError: list index out of range
```
As a workaround I added some text before processing with gerbolyze and removed it afterwards.

**Comment by jaseg** [comment]
Thank you for the report. I've fixed this in master now. It will add a dummy aperture for empty layers now.
