### ISSUE TITLE
Problem with easyEDA files.

### ISSUE THREAD

**Issue by Modalen-Engineering** [jaseg/gerbolyze#44]
I tried multiple gerber files from easyEDA pro on multiple machines.

I get this error.
python -m gerbolyze template --top 294f763686bd4bc0b0d0cfd0dafab3b4_1704711853000.zip output.
svg
Traceback (most recent call last):
  File "C:\Users\Modalen\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Modalen\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Modalen\AppData\Roaming\Python\Python39\site-packages\gerbolyze\__main__.py", line 2, in <module>
    gerbolyze.cli()
  File "C:\Users\Modalen\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Modalen\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Modalen\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Modalen\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Modalen\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Modalen\AppData\Roaming\Python\Python39\site-packages\gerbolyze\__init__.py", line 130, in template
    svg = stack.to_pretty_svg(side=('top' if top else 'bottom'), inkscape=True)
  File "C:\Users\Modalen\AppData\Roaming\Python\Python39\site-packages\gerbonara\layers.py", line 720, in to_pretty_svg
    objects.insert(0, tag('path', id='outline-path', d=self.outline_svg_d(unit=svg_unit), style='fill:white'))
  File "C:\Users\Modalen\AppData\Roaming\Python\Python39\site-packages\gerbonara\layers.py", line 942, in outline_svg_d
    for chain in chains:
  File "C:\Users\Modalen\AppData\Roaming\Python\Python39\site-packages\gerbonara\layers.py", line 972, in outline_polygons
    x_left  = bisect.bisect_left (by_x, x, key=lambda elem: elem[0] + tol)
TypeError: 'key' is an invalid keyword argument for bisect_left()

**Comment by jaseg** [comment]
According to python's doc, the `key` parameter was added to `bisect_left` in Python 3.10, released October 2021. From your stack trace it looks like you're running Python 3.9, which does not have that feature yet. Update your python, and that error should go away.
